name: Ubuntu

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-18.04
    container: massj/ubuntu1804:gcc7
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
      
    - name: Create Build Environment
      shell: bash
      run: make prepare_release

    - name: Configure CMake
      shell: bash
      run: make configure
      
    - name: Build
      shell: bash
      run: make build_release

    - name: Unit Tests with Code Coverage
      working-directory: ${{runner.workspace}}/Pokerbot/
      shell: bash
      run: make coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1