name: Windows

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v2      
    - name: Install Tools
      run: pip install conan
      
    - name: Create Build Environment
      working-directory: ${{runner.workspace}}/Pokerbot
     # run: make prepare_release
      run: conan create . -pr conan_configs/vs17_release

  #  - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
     # shell: bash
     # working-directory: ${{runner.workspace}}/Pokerbot
     # run: make configure
      
  #  - name: Build
     # shell: bash
     # working-directory: ${{runner.workspace}}/Pokerbot
     # run: make build_release

   # - name: Test
    #  working-directory: ${{runner.workspace}}/Pokerbot/build
     # shell: bash
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      #run: ctest -C $BUILD_TYPE
